name = "cf-email-api"
main = "src/index.ts"
compatibility_date = "2026-04-08"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[vars]
DEFAULT_TTL = "600"
DEFAULT_TTL_UNIT = "seconds"
ENABLE_AI = "true"
REQUIRE_AUTH = "false"
FILTER_MODE = "none"
FILTER_LIST = "test"

[[kv_namespaces]]
binding = "EMAIL_KV"
id = "fb2a03033e2245b2a60ed200b02d20d6"

[ai]
binding = "AI"
